### ISSUE TITLE
no rofi launchers

### ISSUE THREAD

**Issue by battlemag3** [dagregi/dotfiles#1]
`
~ ❯ zsh:1: no such file or directory: /home/michael/.config/rofi/launchers/type-4/launcher.sh
`

so, uh. No rofi launchers, have not tested everything else yet

**Comment by dagregi** [comment]
If you're looking for rofi launchers I put them in the `.local/bin/rofi` directory most of the scripts I use are in a different [repo](https://github.com/dagregi/scripts)
